/* Copyright Ion Beam Applications */

/*******************************************************************************
    Description
    -----------
   
    RPCGEN source file for module: ecubtcu1
*******************************************************************************/

/*******************************************************************************
    Modification history
    --------------------
    01,PBR,30Jan2002      DEV-0008  Generated by python script
*******************************************************************************/

typedef char ECUBTCU1_EQUIPMENT_NAME[20];

typedef char ECUBTCU1_DEVICE_NAME[20];

typedef char ECUBTCU1_INDEX_NAME[40];

typedef char ECUBTCU1_CONFIG_DATA[640];

typedef char BPM_DEVICE_NAME[20];

typedef char BS_DEVICE_NAME[20];

typedef char STEPPER_DEVICE_NAME[20];

struct ecubtcu1SetConfiguration_in {
    ECUBTCU1_EQUIPMENT_NAME pEquipmentName;
    ECUBTCU1_DEVICE_NAME pDeviceName;
    ECUBTCU1_INDEX_NAME pParameterName;
    ECUBTCU1_CONFIG_DATA pValue;
};

struct ecubtcu1SetConfiguration_out {
    int returnValue;
};

struct ecubtcu1EndSetConfiguration_out {
    int returnValue;
};

struct ecubtcu1RequestShutdown_out {
    int returnValue;
};

struct bpmInsert_in {
    BPM_DEVICE_NAME pName;
};

struct bpmInsert_out {
    int returnValue;
};

struct bpmRetract_in {
    BPM_DEVICE_NAME pName;
};

struct bpmRetract_out {
    int returnValue;
};

struct bpmCheckInsert_in {
    BPM_DEVICE_NAME pName;
};

struct bpmCheckInsert_out {
    int returnValue;
};

struct bpmCheckRetract_in {
    BPM_DEVICE_NAME pName;
};

struct bpmCheckRetract_out {
    int returnValue;
};

struct group3SetOffset_in {
    double offset;
};

struct group3SetOffset_out {
    int returnValue;
};

struct group3SetGain_in {
    double gain;
};

struct group3SetGain_out {
    int returnValue;
};

struct bsInsert_in {
    BS_DEVICE_NAME pName;
};

struct bsInsert_out {
    int returnValue;
};

struct bsRetract_in {
    BS_DEVICE_NAME pName;
};

struct bsRetract_out {
    int returnValue;
};

struct bsCheckInsert_in {
    BS_DEVICE_NAME pName;
};

struct bsCheckInsert_out {
    int returnValue;
};

struct bsCheckRetract_in {
    BS_DEVICE_NAME pName;
};

struct bsCheckRetract_out {
    int returnValue;
};

struct stepperIoExcite_in {
    STEPPER_DEVICE_NAME pName;
};

struct stepperIoExcite_out {
    int returnValue;
};

struct stepperIoDesexcite_in {
    STEPPER_DEVICE_NAME pName;
};

struct stepperIoDesexcite_out {
    int returnValue;
};

struct stepperIoCheckExcitation_in {
    STEPPER_DEVICE_NAME pName;
};

struct stepperIoCheckExcitation_out {
    int returnValue;
};

program RPC_PROGRAM {
    version RPC_VERSION {
        ecubtcu1SetConfiguration_out ECUBTCU1SETCONFIGURATION(ecubtcu1SetConfiguration_in) = 1;
        ecubtcu1EndSetConfiguration_out ECUBTCU1ENDSETCONFIGURATION(void) = 2;
        ecubtcu1RequestShutdown_out ECUBTCU1REQUESTSHUTDOWN(void) = 3;
        bpmInsert_out BPMINSERT(bpmInsert_in) = 4;
        bpmRetract_out BPMRETRACT(bpmRetract_in) = 5;
        bpmCheckInsert_out BPMCHECKINSERT(bpmCheckInsert_in) = 6;
        bpmCheckRetract_out BPMCHECKRETRACT(bpmCheckRetract_in) = 7;
        group3SetOffset_out GROUP3SETOFFSET(group3SetOffset_in) = 8;
        group3SetGain_out GROUP3SETGAIN(group3SetGain_in) = 9;
        bsInsert_out BSINSERT(bsInsert_in) = 10;
        bsRetract_out BSRETRACT(bsRetract_in) = 11;
        bsCheckInsert_out BSCHECKINSERT(bsCheckInsert_in) = 12;
        bsCheckRetract_out BSCHECKRETRACT(bsCheckRetract_in) = 13;
        stepperIoExcite_out STEPPERIOEXCITE(stepperIoExcite_in) = 14;
        stepperIoDesexcite_out STEPPERIODESEXCITE(stepperIoDesexcite_in) = 15;
        stepperIoCheckExcitation_out STEPPERIOCHECKEXCITATION(stepperIoCheckExcitation_in) = 16;
    } = 1;
} = 55555555;

